import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.Random;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class SeleniumTestLogin {
    /*
    private static WebDriver driver = null;
    private WebDriverWait webDriverWait = null;
    private Random random = new Random();

    @BeforeClass
    public static void setUpClass() {
        System.setProperty("webdriver.gecko.driver", "");
        driver = new FirefoxDriver();
    }


    @Test
    public void testLogin() {
        webDriverWait = new WebDriverWait(driver, 10);
        driver.get("http://sepp-test.inf.h-brs.de:8080/gibraldaapp-0.0.1-SNAPSHOT/");
        //driver.get("localhost:8080");
        driver.manage().window().maximize();
        webDriverWait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div[2]/vaadin-vertical-layout/vaadin-login-form/vaadin-login-form-wrapper/form/vaadin-text-field/input")));
        driver.findElement(By.xpath("/html/body/div[2]/vaadin-vertical-layout/vaadin-login-form/vaadin-login-form-wrapper/form/vaadin-text-field/input")).sendKeys("ubisoft@bug.de");
        driver.findElement(By.xpath("/html/body/div[2]/vaadin-vertical-layout/vaadin-login-form/vaadin-login-form-wrapper/form/vaadin-password-field/input")).sendKeys("Test1234");
        driver.findElement(By.xpath("/html/body/div[2]/vaadin-vertical-layout/vaadin-login-form/vaadin-login-form-wrapper/form/vaadin-button")).click();
        webDriverWait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/vaadin-app-layout/vaadin-horizontal-layout/vaadin-horizontal-layout/h3")));
        assertEquals(driver.findElement(By.xpath("/html/body/vaadin-app-layout/vaadin-horizontal-layout/vaadin-horizontal-layout/h3")).getText(), "Hallo Ubisoft!");

        //webDriverWait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//[@id="button"]")));
        /*try{
            driver.findElement(By.xpath("")).click(); //Button aus irgendeinem Grund leider nicht interactable
        }catch (ElementNotInteractableException e) {
            WebElement webElement = driver.findElement(By.xpath(""));
            Actions actions = new Actions(driver);
            actions.moveToElement(webElement).click();
        }
    }

    @Test
    public void testRegister(){
        webDriverWait = new WebDriverWait(driver, 10, 2000);
        driver.get("localhost:8080");
        driver.manage().window().maximize();
        webDriverWait.until(ExpectedConditions.visibilityOf(driver.findElement(By.xpath("//*[@id=\"register-link\"]"))));
        driver.findElement(By.xpath("//*[@id=\"register-link2\"]")).click();
        webDriverWait.until(ExpectedConditions.visibilityOf(driver.findElement(By.xpath("//*[@id=\"title\"]"))));

        driver.findElement(By.xpath("//*[@id=\"telefonnummer\"]")).sendKeys("AutoGenerated");
        driver.findElement(By.xpath("//*[@id=\"telefonnummer\"]")).sendKeys("123456789012");
        driver.findElement(By.xpath("//*[@id=\"strasse\"]")).sendKeys("AutoGenerated");
        driver.findElement(By.xpath("//*[@id=\"hausnummer\"]")).sendKeys("1");
        driver.findElement(By.xpath("//*[@id=\"plz\"]")).sendKeys("11111");
        driver.findElement(By.xpath("//*[@id=\"ort\"]")).sendKeys("AutoGenerated");
        driver.findElement(By.xpath("//*[@id=\"emailadresse\"]")).sendKeys("autogenerated"+random.nextInt()+"@web.de");
        driver.findElement(By.xpath("//*[@id=\"passwort\"]")).sendKeys("Autogenerated1");
        driver.findElement(By.xpath("//*[@id=\"passwortwiederholen\"]")).sendKeys("Autogenerated1");
        driver.findElement(By.xpath("//*[@id=\"registrieren-button\"]")).click();

    }

    @AfterClass
    public static void tearDownClass(){
        driver.quit();
    }


    */

}
